module Ryac
  module UnionFind
    @parent: Hash[method_key, method_key]
    @rank: Hash[method_key, Integer]

    def uf_init: () -> void
    def uf_root: (method_key key) -> method_key
    def merge_groups: (method_key key1, method_key key2) -> void

    private

    def uf_add: (method_key key) -> method_key
    def uf_remove: (method_key key) -> void
  end
end
