# frozen_string_literal: true

require_relative '../test_helper'

class TestDriverFile < Minitest::Test
  HEADER_PIN = <<~'RUBY'
    # Generated by ryac. Usage: ruby driver.rb CORE [--exec EXPR] [ARGS...]
    # Loads CORE, registers the regions below, then evals EXPR at top level
    # with ARGS left in ARGV. Arguments after "--" are never read.
    core = ARGV.shift or abort("usage: ruby #{$0} CORE [--exec EXPR] [ARGS...]")
    stop = ARGV.index("--")
    at = ARGV.index("--exec")
    expr = ARGV.slice!(at, 2)[1] if at && (!stop || at < stop)
    load core
  RUBY

  FOOTER_PIN = "eval(expr, TOPLEVEL_BINDING, \"--exec\") if expr\n"

  def test_runner_text_pinned
    assert_equal HEADER_PIN, Ryac::DriverFile::HEADER
    assert_equal FOOTER_PIN, Ryac::DriverFile::FOOTER
  end

  # The registrations, and only they, move to the runner — one per line,
  # between the header that loads the core and the footer that starts the
  # program; everything else stays the core in its original order.
  def test_split_moves_the_registrations_to_the_runner
    full = 'require "set";A={};def b(a) =(x);A["plugins/x"]=->{module M;class X;end;end};' \
           'A["plugins/y"]=->{Y=1};module M;class K;end;end;Foo=M'
    core, driver = Ryac::DriverFile.split(full)
    assert_equal 'require "set";A={};def b(a) =(x);module M;class K;end;end;Foo=M', core
    assert_equal "#{HEADER_PIN}A[\"plugins/x\"]=->{module M;class X;end;end}\nA[\"plugins/y\"]=->{Y=1}\n#{FOOTER_PIN}",
                 driver
  end

  def test_split_needs_a_region
    error = assert_raises(Ryac::MinifyError) { Ryac::DriverFile.split('puts 1') }
    assert_equal 'cannot write a driver file: the program has no lazy regions', error.message
  end
end
