# frozen_string_literal: true

require_relative 'level_test_helper'

class TestLevel5 < Minitest::Test
  include MinifyTestHelper
  include LevelTestHelper

  # L5: Full renaming (locals + keywords + ivars + cvars + gvars + methods)
  def test_level_5
    result = minify_at_level(LEVEL_TEST_CODE, 5)
    expected = [
      "module B;I=5;S=1000000000000000000;",
      "def self.a(a) =a*I*S;",
      "def self.b(a,b,c) =a<b ? b : a>c ? c : a;",
      "end;",
      "class R;",
      "def o =\"base\";",
      "end;",
      "class A<R;L=256;Q=%w[low medium high].freeze;P=%i[add subtract multiply].freeze;",
      "attr :p;",
      "attr :b1,!!1;",
      "def initialize(b,a:\"default\") =(@p=b;@b1=a;@a=[];@@a||=0;@@a+=1;$a=self);",
      "def t(b,a:!1) =(@p=@p+b;@a.push b;a ? \"added\":\"silent\");",
      "def subtract_number(a) =@p-a;",
      "alias neg subtract_number;",
      "def m =@p*A::L;",
      "def a4 =(@p=0;a=0;a+=1 while a<3;$a=nil;a);",
      "def y =?x;",
      "def g =@p>100?\"big\":\"small\";",
      "def x =(\"non-positive\" unless @p>0);",
      "def process_items(a) =a.each{puts _1};",
      "def a3(a) =begin;@p/a;rescue ZeroDivisionError;0;ensure;@a.push :divide;",
      "end;",
      "def w =case @p;when (0..10);\"low\";when (11..100);\"medium\";else;\"high\";",
      "end;",
      "def r =\"\#{@b1}: \#{@p}\";",
      "def to_s =\"Calculator(\#{@p})\";",
      "def o =super;",
      "def a8 =(yield @p if block_given?);",
      "def b0(a) =(b=[];c=0;until c>=a;c+=1;next if c==2;break if c>4;b.push c;",
      "end;b);",
      "def a0 =(a=0;begin;a+=1;fail \"fail\" if a<2;a;rescue;retry if a<2;0;end);",
      "def z =defined?(@p)?\"yes\":\"no\";",
      "def h(a,b) =(a and !b)?\"a only\":(a or b)?\"at least one\":\"none\";",
      "def n(a) =a&.to_s;",
      "def c(a) =(return \"negative\" if a<0;return \"zero\" if a==0;\"positive\");",
      "def a1;a,*b=1,2,3,4;a+b.size;",
      "end;",
      "def a7(*a,**b) =a.size+b.size;",
      "def a6(&a) =(a.call @p if a);",
      "def a5 =(a=->(val){val*2};a.call @p);",
      "def v =(a=\"hello\\nworld\\n\";a.strip);",
      "def i(a) =a=~/^calc/i?!!1 : !1;",
      "def a9 =(a=0;for b in [10,20,30];a+=b;",
      "end;a);",
      "def d =(Integer(\"abc\") rescue 0);",
      "def e(a) =!a ? \"nil\":a.to_s;",
      "def b(a) =[1,(2 if a),3].compact;",
      "def q(a) =a.match(/=\\d+/);",
      "def a(a) =(if a;b,c=1,2;else;b,c=3,4;",
      "end;b+c);",
      "def l =[1,2,3].select{|a,b=true|b};",
      "def s =[1,2].map{|b,&a|a ? a.call(b):b};",
      "def u =[[1,2,3]].map{|b,*a|b+a.length};",
      "def k =[{a:1}].each{|b,a:false|puts b.inspect};",
      "define_singleton_method(:dsl_method){|a=true|a ? \"yes\":\"no\"};",
      "def f ={[:a,1]=>?x}.each{|(b,c),a|puts \"\#{b}\#{c}\#{a}\"};",
      "def a2 =send :g;",
      "def j(a=nil,&b) =(def b.each =yield call;b);",
      "end;",
      "class K;",
      "def b(c,a:\"\",b:\"\") =\"\#{a}\#{c}\#{b}\";",
      "def a(a) =a==!!1 ? \"yes\":\"no\";",
      "end;",
      "class E;",
      "attr :timeout_ms,!!1;",
      "attr :retry_limit;",
      "def initialize =(@timeout_ms=100;@retry_limit=3);",
      "end;",
      "class G;",
      "def bump_timeout(a) =a.timeout_ms=500;",
      "def raise_timeout(a) =a.timeout_ms+=250;",
      "def show_retries(a) =puts a.retry_limit;",
      "end;",
      "class F;include Comparable;",
      "attr :version_number;",
      "def initialize(a) =@version_number=a;",
      "def <=>(a) =version_number<=>a.version_number;",
      "end;",
      "class M;",
      "attr :payload_data;",
      "attr_writer :payload_data;",
      "def initialize =@payload_data=1;",
      "end;",
      "class C;",
      "def initialize =@secret_value=42;",
      "def b(other) =other.instance_eval{@secret_value};",
      "def a(a) =instance_variable_get \"@\"+a;",
      "end;",
      "class D;",
      "def initialize =@a=?w;",
      "define_method(:show_label){@a};",
      "end;",
      "class N;",
      "def self.a(a) =a+10;",
      "end;",
      "class J;",
      "def self.a(a) =a*2;",
      "end;H=[N,J].freeze;calc=A.new 10,a:\"main\";calc.t 5,a:!!1;calc.t 3,a:!1;",
      "puts calc.subtract_number(2);",
      "puts calc.neg(1);",
      "puts calc.m;",
      "puts calc.a4;",
      "puts A::L;",
      "puts calc.y;",
      "puts calc.g;",
      "puts calc.x;",
      "puts calc.a3(0);",
      "puts calc.w;",
      "puts calc.r;",
      "puts calc.to_s;",
      "puts calc.o;calc.a8{puts _1};",
      "puts calc.b0(5).inspect;",
      "puts calc.a0;",
      "puts calc.z;",
      "puts calc.h(!!1,!1);",
      "puts calc.h(!1,!!1);",
      "puts calc.h(!1,!1);",
      "puts calc.n(\"hello\");",
      "puts calc.n(nil);",
      "puts calc.c(-1);",
      "puts calc.c(0);",
      "puts calc.c(1);",
      "puts calc.a1;",
      "puts calc.a7(1,2,3,a:4);puts(calc.a6{_1+100});",
      "puts calc.a5;",
      "puts calc.v;",
      "puts calc.i(\"calculator\");",
      "puts calc.i(\"other\");",
      "puts calc.a9;",
      "puts calc.d;",
      "puts calc.e(nil);",
      "puts calc.e(\"hi\");",
      "puts calc.b(!!1).inspect;",
      "puts calc.b(!1).inspect;",
      "puts calc.q(\"x=42\");",
      "puts calc.q(\"hello\");",
      "puts calc.a(!!1);",
      "puts calc.a(!1);",
      "puts calc.l.inspect;",
      "puts calc.s.inspect;",
      "puts calc.u.inspect;calc.k;",
      "puts A.dsl_method;",
      "puts A.dsl_method(!1);",
      "puts calc.a2;calc.f;puts(calc.j{\"hello\"}.class);",
      "puts B::I;",
      "puts B.a(7);",
      "puts B.b(150,0,100);fmt=K.new;",
      "puts fmt.b(42,a:\"$\",b:\"!\");",
      "puts fmt.a(!!1);",
      "puts fmt.a(!1);doubled=B.a A::L;",
      "puts doubled;",
      "puts A::Q.inspect;",
      "puts A::P.inspect;",
      "puts O::Status.name;",
      "puts O::Sys.name;",
      "puts O::UID.name;",
      "puts O::GID.name;config=E.new;G.new;",
      "puts config.timeout_ms;",
      "puts config.retry_limit;",
      "puts F.new(1)<F.new(2);payload=M.new;payload.payload_data=9;",
      "puts payload.payload_data;holder=C.new;",
      "puts holder.b(C.new);",
      "puts holder.a(\"secret_value\");",
      "puts D.new.show_label;puts(H.reduce(5){_2.a _1})",
    ].join('')
    assert_equal expected, result.code
    assert_equal 'O=Process', result.preamble
    assert_equal 'AddStep=N;Base=R;Calculator=A;DoubleStep=J;Formatter=K;LabeledWidget=D;MathUtils=B;PIPELINE_STEPS=H;Payload=M;SecretHolder=C;TimeoutConfig=E;TimeoutTuner=G;VersionTag=F;A::LABELS=A::Q;A::OFFSET=A::L;A::SYMBOLS=A::P;B::MULTIPLIER=B::I', result.aliases
  end
end
