# frozen_string_literal: true

require_relative 'level_test_helper'

class TestLevel2 < Minitest::Test
  include MinifyTestHelper
  include LevelTestHelper

  # L2: Constant aliasing (value constants only) — MULTIPLIER→A, OFFSET→B, SYMBOLS→C, LABELS→D
  # Class/module names stay original: MathUtils, Base, Calculator, Formatter
  def test_level_2
    result = minify_at_level(LEVEL_TEST_CODE, 2)
    expected = [
      "module MathUtils;A=5;S=1000000000000000000;",
      "def self.double_value(number) =number*A*S;",
      "def self.clamp_value(value,min_val,max_val) =value<min_val ? min_val : value>max_val ? max_val : value;",
      "end;",
      "class Base;",
      "def parent_info =\"base\";",
      "end;",
      "class Calculator<Base;B=256;E=%w[low medium high].freeze;D=%i[add subtract multiply].freeze;",
      "attr :current_value;",
      "attr :label,!!1;",
      "def initialize(initial_value,label:\"default\") =(@current_value=initial_value;@label=label;@history=[];@@instance_count||=0;@@instance_count+=1;$last_calculator=self);",
      "def add_number(amount,verbose:!1) =(@current_value=@current_value+amount;@history.push amount;verbose ? \"added\":\"silent\");",
      "def subtract_number(amount) =@current_value-amount;",
      "alias neg subtract_number;",
      "def multiply_by_offset =@current_value*Calculator::B;",
      "def reset_value =(@current_value=0;counter=0;counter+=1 while counter<3;$last_calculator=nil;counter);",
      "def get_separator =?x;",
      "def describe_value =@current_value>100?\"big\":\"small\";",
      "def check_positive =(\"non-positive\" unless @current_value>0);",
      "def process_items(items) =items.each{|item|puts item};",
      "def safe_divide(divisor) =begin;@current_value/divisor;rescue ZeroDivisionError;0;ensure;@history.push :divide;",
      "end;",
      "def classify_value =case @current_value;when (0..10);",
      "\"low\";when (11..100);",
      "\"medium\";else;\"high\";",
      "end;",
      "def value_with_label =\"\#{@label}: \#{@current_value}\";",
      "def to_s =\"Calculator(\#{@current_value})\";",
      "def parent_info =super;",
      "def with_yield =(yield @current_value if block_given?);",
      "def count_up(limit) =(result=[];idx=0;until idx>=limit;idx+=1;next if idx==2;break if idx>4;result.push idx;",
      "end;result);",
      "def retry_example =(attempts=0;begin;attempts+=1;raise \"fail\" if attempts<2;attempts;rescue;retry if attempts<2;0;end);",
      "def check_defined =defined?(@current_value)?\"yes\":\"no\";",
      "def logic_test(flag_a,flag_b) =(flag_a and !flag_b)?\"a only\":(flag_a or flag_b)?\"at least one\":\"none\";",
      "def safe_access(obj) =obj&.to_s;",
      "def return_early(value) =(return \"negative\" if value<0;return \"zero\" if value==0;\"positive\");",
      "def multi_assign;first,*rest=1,2,3,4;first+rest.length;",
      "end;",
      "def splat_args(*args,**kwargs) =args.length+kwargs.length;",
      "def with_block(&block) =(block.call @current_value if block);",
      "def use_lambda =(fn=->(val){val*2};fn.call @current_value);",
      "def heredoc_example =(text=\"hello\\nworld\\n\";text.strip);",
      "def regex_example(input) =input=~/^calc/i?!!1 : !1;",
      "def for_loop =(total=0;for num in [10,20,30];total+=num;",
      "end;total);",
      "def rescue_modifier_example =(Integer(\"abc\") rescue 0);",
      "def negated_ternary(val) =!val ? \"nil\":val.to_s;",
      "def array_with_conditional(flag) =[1,(2 if flag),3].compact;",
      "def regex_match(str) =str.match(/=\\d+/);",
      "def multi_assign_conditional(flag) =(if flag;a,b=1,2;else;a,b=3,4;",
      "end;a+b);",
      "def with_block_default =[1,2,3].select{|val,keep=true|keep};",
      "def with_block_param =[1,2].map{|num,&callback|callback ? callback.call(num):num};",
      "def with_rest_param =[[1,2,3]].map{|first,*rest|first+rest.length};",
      "def with_keyword_param =[{a:1}].each{|val,flag:false|puts val.inspect};",
      "define_singleton_method(:dsl_method){|verbose=true|verbose ? \"yes\":\"no\"};",
      "def destructured_iteration ={[:a,1]=>?x}.each{|(sym,num),label|puts \"\#{sym}\#{num}\#{label}\"};",
      "def send_example =send :describe_value;",
      "def wrap_in_enumerator(value=nil,&block) =(def block.each =yield call;block);",
      "end;",
      "class Formatter;",
      "def format_number(value,prefix:\"\",suffix:\"\") =\"\#{prefix}\#{value}\#{suffix}\";",
      "def format_flag(flag) =flag==!!1 ? \"yes\":\"no\";",
      "end;",
      "calc=Calculator.new 10,label:\"main\";calc.add_number 5,verbose:!!1;calc.add_number 3,verbose:!1;",
      "puts calc.subtract_number(2);",
      "puts calc.neg(1);",
      "puts calc.multiply_by_offset;",
      "puts calc.reset_value;",
      "puts Calculator::B;",
      "puts calc.get_separator;",
      "puts calc.describe_value;",
      "puts calc.check_positive;",
      "puts calc.safe_divide(0);",
      "puts calc.classify_value;",
      "puts calc.value_with_label;",
      "puts calc.to_s;",
      "puts calc.parent_info;calc.with_yield{|v|puts v};",
      "puts calc.count_up(5).inspect;",
      "puts calc.retry_example;",
      "puts calc.check_defined;",
      "puts calc.logic_test(!!1,!1);",
      "puts calc.logic_test(!1,!!1);",
      "puts calc.logic_test(!1,!1);",
      "puts calc.safe_access(\"hello\");",
      "puts calc.safe_access(nil);",
      "puts calc.return_early(-1);",
      "puts calc.return_early(0);",
      "puts calc.return_early(1);",
      "puts calc.multi_assign;",
      "puts calc.splat_args(1,2,3,a:4);",
      "puts(calc.with_block{|v|v+100});",
      "puts calc.use_lambda;",
      "puts calc.heredoc_example;",
      "puts calc.regex_example(\"calculator\");",
      "puts calc.regex_example(\"other\");",
      "puts calc.for_loop;",
      "puts calc.rescue_modifier_example;",
      "puts calc.negated_ternary(nil);",
      "puts calc.negated_ternary(\"hi\");",
      "puts calc.array_with_conditional(!!1).inspect;",
      "puts calc.array_with_conditional(!1).inspect;",
      "puts calc.regex_match(\"x=42\");",
      "puts calc.regex_match(\"hello\");",
      "puts calc.multi_assign_conditional(!!1);",
      "puts calc.multi_assign_conditional(!1);",
      "puts calc.with_block_default.inspect;",
      "puts calc.with_block_param.inspect;",
      "puts calc.with_rest_param.inspect;calc.with_keyword_param;",
      "puts Calculator.dsl_method;",
      "puts Calculator.dsl_method(!1);",
      "puts calc.send_example;",
      "calc.destructured_iteration;puts(calc.wrap_in_enumerator{\"hello\"}.class);",
      "puts MathUtils::A;",
      "puts MathUtils.double_value(7);",
      "puts MathUtils.clamp_value(150,0,100);",
      "fmt=Formatter.new;",
      "puts fmt.format_number(42,prefix:\"$\",suffix:\"!\");",
      "puts fmt.format_flag(!!1);",
      "puts fmt.format_flag(!1);",
      "doubled=MathUtils.double_value Calculator::B;",
      "puts doubled;",
      "puts Calculator::E.inspect;",
      "puts Calculator::D.inspect;",
      "puts C::Status.name;",
      "puts C::Sys.name;",
      "puts C::UID.name;",
      "puts C::GID.name"
    ].join('')
    assert_equal expected, result.code
    assert_equal 'C=Process', result.preamble
    assert_equal 'Calculator::LABELS=Calculator::E;Calculator::OFFSET=Calculator::B;Calculator::SYMBOLS=Calculator::D;MathUtils::MULTIPLIER=MathUtils::A', result.aliases
  end
end
