# frozen_string_literal: true

require_relative 'level_test_helper'

class TestLevel5 < Minitest::Test
  include MinifyTestHelper
  include LevelTestHelper

  # L5: Full renaming (locals + keywords + ivars + cvars + gvars + methods)
  def test_level_5
    result = minify_at_level(LEVEL_TEST_CODE, 5)
    expected = [
      "module B;C=5;S=1000000000000000000;",
      "def self.a(a) =a*C*S;",
      "def self.b(a,b,c) =a<b ? b : a>c ? c : a;",
      "end;",
      "class I;",
      "def q =\"base\";",
      "end;",
      "class A<I;E=256;H=%w[low medium high].freeze;G=%i[add subtract multiply].freeze;attr :p;attr :b1,!!1;",
      "def initialize(b,a:\"default\") =(@p=b;@b1=a;@a=[];@@a||=0;@@a+=1;$a=self);",
      "def t(b,a:!1) =(@p=@p+b;@a.push b;a ? \"added\":\"silent\");",
      "def subtract_number(a) =@p-a;",
      "alias neg subtract_number;",
      "def l =@p*A::E;",
      "def a4 =(@p=0;a=0;a+=1 while a<3;$a=nil;a);",
      "def y =?x;",
      "def g =@p>100?\"big\":\"small\";",
      "def w =(\"non-positive\" unless @p>0);",
      "def process_items(a) =a.each{puts _1};",
      "def a3(a) =begin;@p/a;rescue ZeroDivisionError;0;ensure;@a.push :divide;",
      "end;",
      "def x =case @p;when (0..10);",
      "\"low\";when (11..100);",
      "\"medium\";else;\"high\";",
      "end;",
      "def s =\"\#{@b1}: \#{@p}\";",
      "def to_s =\"Calculator(\#{@p})\";",
      "def q =super;",
      "def a5 =(yield @p if block_given?);",
      "def b0(a) =(b=[];c=0;until c>=a;c+=1;next if c==2;break if c>4;b.push c;",
      "end;b);",
      "def z =(a=0;begin;a+=1;fail \"fail\" if a<2;a;rescue;retry if a<2;0;end);",
      "def a0 =defined?(@p)?\"yes\":\"no\";",
      "def h(a,b) =(a and !b)?\"a only\":(a or b)?\"at least one\":\"none\";",
      "def o(a) =a&.to_s;",
      "def c(a) =(return \"negative\" if a<0;return \"zero\" if a==0;\"positive\");",
      "def a1;a,*b=1,2,3,4;a+b.size;",
      "end;",
      "def a8(*a,**b) =a.size+b.size;",
      "def a7(&a) =(a.call @p if a);",
      "def a6 =(a=->(val){val*2};a.call @p);",
      "def v =(a=\"hello\\nworld\\n\";a.strip);",
      "def i(a) =a=~/^calc/i?!!1 : !1;",
      "def a9 =(a=0;for b in [10,20,30];a+=b;",
      "end;a);",
      "def d =(Integer(\"abc\") rescue 0);",
      "def e(a) =!a ? \"nil\":a.to_s;",
      "def b(a) =[1,(2 if a),3].compact;",
      "def n(a) =a.match(/=\\d+/);",
      "def a(a) =(if a;b,c=1,2;else;b,c=3,4;",
      "end;b+c);",
      "def j =[1,2,3].select{|a,b=true|b};",
      "def r =[1,2].map{|a,&d|d ? d.call(a):a};",
      "def u =[[1,2,3]].map{|a,*d|a+d.length};",
      "def k =[{a:1}].each{|a,d:false|puts a.inspect};",
      "define_singleton_method(:dsl_method){|a=true|a ? \"yes\":\"no\"};",
      "def f ={[:a,1]=>?x}.each{|(e,f),d|puts \"\#{e}\#{f}\#{d}\"};",
      "def a2 =send :g;",
      "def m(a=nil,&b) =(def b.each =yield call;b);",
      "end;",
      "class D;",
      "def b(c,a:\"\",b:\"\") =\"\#{a}\#{c}\#{b}\";",
      "def a(a) =a==!!1 ? \"yes\":\"no\";",
      "end;a=A.new 10,a:\"main\";a.t 5,a:!!1;a.t 3,a:!1;",
      "puts a.subtract_number(2);",
      "puts a.neg(1);",
      "puts a.l;",
      "puts a.a4;",
      "puts A::E;",
      "puts a.y;",
      "puts a.g;",
      "puts a.w;",
      "puts a.a3(0);",
      "puts a.x;",
      "puts a.s;",
      "puts a.to_s;",
      "puts a.q;a.a5{puts _1};",
      "puts a.b0(5).inspect;",
      "puts a.z;",
      "puts a.a0;",
      "puts a.h(!!1,!1);",
      "puts a.h(!1,!!1);",
      "puts a.h(!1,!1);",
      "puts a.o(\"hello\");",
      "puts a.o(nil);",
      "puts a.c(-1);",
      "puts a.c(0);",
      "puts a.c(1);",
      "puts a.a1;",
      "puts a.a8(1,2,3,a:4);",
      "puts(a.a7{_1+100});",
      "puts a.a6;",
      "puts a.v;",
      "puts a.i(\"calculator\");",
      "puts a.i(\"other\");",
      "puts a.a9;",
      "puts a.d;",
      "puts a.e(nil);",
      "puts a.e(\"hi\");",
      "puts a.b(!!1).inspect;",
      "puts a.b(!1).inspect;",
      "puts a.n(\"x=42\");",
      "puts a.n(\"hello\");",
      "puts a.a(!!1);",
      "puts a.a(!1);",
      "puts a.j.inspect;",
      "puts a.r.inspect;",
      "puts a.u.inspect;a.k;",
      "puts A.dsl_method;",
      "puts A.dsl_method(!1);",
      "puts a.a2;",
      "a.f;puts(a.m{\"hello\"}.class);",
      "puts B::C;",
      "puts B.a(7);",
      "puts B.b(150,0,100);",
      "b=D.new;",
      "puts b.b(42,a:\"$\",b:\"!\");",
      "puts b.a(!!1);",
      "puts b.a(!1);",
      "c=B.a A::E;",
      "puts c;",
      "puts A::H.inspect;",
      "puts A::G.inspect;",
      "puts F::Status.name;",
      "puts F::Sys.name;",
      "puts F::UID.name;",
      "puts F::GID.name"
    ].join('')
    assert_equal expected, result.code
    assert_equal 'F=Process', result.preamble
    assert_equal 'Base=I;Calculator=A;Formatter=D;MathUtils=B;A::LABELS=A::H;A::OFFSET=A::E;A::SYMBOLS=A::G;B::MULTIPLIER=B::C', result.aliases
  end
end
