# frozen_string_literal: true

require_relative 'level_test_helper'

class TestLevel3 < Minitest::Test
  include MinifyTestHelper
  include LevelTestHelper

  # L3: Variable renaming (locals + keywords), value constant aliasing
  # Class/module names stay original
  def test_level_3
    result = minify_at_level(LEVEL_TEST_CODE, 3)
    expected = [
      "module MathUtils;A=5;S=1000000000000000000;",
      "def self.double_value(a) =a*A*S;",
      "def self.clamp_value(a,b,c) =a<b ? b : a>c ? c : a;",
      "end;",
      "class Base;",
      "def parent_info =\"base\";",
      "end;",
      "class Calculator<Base;B=256;E=%w[low medium high].freeze;D=%i[add subtract multiply].freeze;",
      "attr :current_value;",
      "attr :label,!!1;",
      "def initialize(b,a:\"default\") =(@current_value=b;@label=a;@history=[];@@instance_count||=0;@@instance_count+=1;$last_calculator=self);",
      "def add_number(b,a:!1) =(@current_value=@current_value+b;@history.push b;a ? \"added\":\"silent\");",
      "def subtract_number(a) =@current_value-a;",
      "alias neg subtract_number;",
      "def multiply_by_offset =@current_value*Calculator::B;",
      "def reset_value =(@current_value=0;a=0;a+=1 while a<3;$last_calculator=nil;a);",
      "def get_separator =?x;",
      "def describe_value =@current_value>100?\"big\":\"small\";",
      "def check_positive =(\"non-positive\" unless @current_value>0);",
      "def process_items(a) =a.each{puts _1};",
      "def safe_divide(a) =begin;@current_value/a;rescue ZeroDivisionError;0;ensure;@history.push :divide;",
      "end;",
      "def classify_value =case @current_value;when (0..10);",
      "\"low\";when (11..100);",
      "\"medium\";else;\"high\";",
      "end;",
      "def value_with_label =\"\#{@label}: \#{@current_value}\";",
      "def to_s =\"Calculator(\#{@current_value})\";",
      "def parent_info =super;",
      "def with_yield =(yield @current_value if block_given?);",
      "def count_up(a) =(b=[];c=0;until c>=a;c+=1;next if c==2;break if c>4;b.push c;",
      "end;b);",
      "def retry_example =(a=0;begin;a+=1;raise \"fail\" if a<2;a;rescue;retry if a<2;0;end);",
      "def check_defined =defined?(@current_value)?\"yes\":\"no\";",
      "def logic_test(a,b) =(a and !b)?\"a only\":(a or b)?\"at least one\":\"none\";",
      "def safe_access(a) =a&.to_s;",
      "def return_early(a) =(return \"negative\" if a<0;return \"zero\" if a==0;\"positive\");",
      "def multi_assign;a,*b=1,2,3,4;a+b.length;",
      "end;",
      "def splat_args(*a,**b) =a.length+b.length;",
      "def with_block(&a) =(a.call @current_value if a);",
      "def use_lambda =(a=->(val){val*2};a.call @current_value);",
      "def heredoc_example =(a=\"hello\\nworld\\n\";a.strip);",
      "def regex_example(a) =a=~/^calc/i?!!1 : !1;",
      "def for_loop =(a=0;for b in [10,20,30];a+=b;",
      "end;a);",
      "def rescue_modifier_example =(Integer(\"abc\") rescue 0);",
      "def negated_ternary(a) =!a ? \"nil\":a.to_s;",
      "def array_with_conditional(a) =[1,(2 if a),3].compact;",
      "def regex_match(a) =a.match(/=\\d+/);",
      "def multi_assign_conditional(a) =(if a;b,c=1,2;else;b,c=3,4;",
      "end;b+c);",
      "def with_block_default =[1,2,3].select{|a,b=true|b};",
      "def with_block_param =[1,2].map{|a,&d|d ? d.call(a):a};",
      "def with_rest_param =[[1,2,3]].map{|a,*d|a+d.length};",
      "def with_keyword_param =[{a:1}].each{|a,d:false|puts a.inspect};",
      "define_singleton_method(:dsl_method){|a=true|a ? \"yes\":\"no\"};",
      "def destructured_iteration ={[:a,1]=>?x}.each{|(e,f),d|puts \"\#{e}\#{f}\#{d}\"};",
      "def send_example =send :describe_value;",
      "def wrap_in_enumerator(a=nil,&b) =(def b.each =yield call;b);",
      "end;",
      "class Formatter;",
      "def format_number(c,a:\"\",b:\"\") =\"\#{a}\#{c}\#{b}\";",
      "def format_flag(a) =a==!!1 ? \"yes\":\"no\";",
      "end;a=Calculator.new 10,a:\"main\";a.add_number 5,a:!!1;a.add_number 3,a:!1;",
      "puts a.subtract_number(2);",
      "puts a.neg(1);",
      "puts a.multiply_by_offset;",
      "puts a.reset_value;",
      "puts Calculator::B;",
      "puts a.get_separator;",
      "puts a.describe_value;",
      "puts a.check_positive;",
      "puts a.safe_divide(0);",
      "puts a.classify_value;",
      "puts a.value_with_label;",
      "puts a.to_s;",
      "puts a.parent_info;a.with_yield{puts _1};",
      "puts a.count_up(5).inspect;",
      "puts a.retry_example;",
      "puts a.check_defined;",
      "puts a.logic_test(!!1,!1);",
      "puts a.logic_test(!1,!!1);",
      "puts a.logic_test(!1,!1);",
      "puts a.safe_access(\"hello\");",
      "puts a.safe_access(nil);",
      "puts a.return_early(-1);",
      "puts a.return_early(0);",
      "puts a.return_early(1);",
      "puts a.multi_assign;",
      "puts a.splat_args(1,2,3,a:4);",
      "puts(a.with_block{_1+100});",
      "puts a.use_lambda;",
      "puts a.heredoc_example;",
      "puts a.regex_example(\"calculator\");",
      "puts a.regex_example(\"other\");",
      "puts a.for_loop;",
      "puts a.rescue_modifier_example;",
      "puts a.negated_ternary(nil);",
      "puts a.negated_ternary(\"hi\");",
      "puts a.array_with_conditional(!!1).inspect;",
      "puts a.array_with_conditional(!1).inspect;",
      "puts a.regex_match(\"x=42\");",
      "puts a.regex_match(\"hello\");",
      "puts a.multi_assign_conditional(!!1);",
      "puts a.multi_assign_conditional(!1);",
      "puts a.with_block_default.inspect;",
      "puts a.with_block_param.inspect;",
      "puts a.with_rest_param.inspect;a.with_keyword_param;",
      "puts Calculator.dsl_method;",
      "puts Calculator.dsl_method(!1);",
      "puts a.send_example;",
      "a.destructured_iteration;puts(a.wrap_in_enumerator{\"hello\"}.class);",
      "puts MathUtils::A;",
      "puts MathUtils.double_value(7);",
      "puts MathUtils.clamp_value(150,0,100);",
      "b=Formatter.new;",
      "puts b.format_number(42,a:\"$\",b:\"!\");",
      "puts b.format_flag(!!1);",
      "puts b.format_flag(!1);",
      "c=MathUtils.double_value Calculator::B;",
      "puts c;",
      "puts Calculator::E.inspect;",
      "puts Calculator::D.inspect;",
      "puts C::Status.name;",
      "puts C::Sys.name;",
      "puts C::UID.name;",
      "puts C::GID.name"
    ].join('')
    assert_equal expected, result.code
    assert_equal 'C=Process', result.preamble
    assert_equal 'Calculator::LABELS=Calculator::E;Calculator::OFFSET=Calculator::B;Calculator::SYMBOLS=Calculator::D;MathUtils::MULTIPLIER=MathUtils::A', result.aliases
  end
end
