# frozen_string_literal: true

require_relative 'level_test_helper'

class TestLevel5 < Minitest::Test
  include MinifyTestHelper
  include LevelTestHelper

  # L5: Full renaming (locals + keywords + ivars + cvars + gvars + methods)
  def test_level_5
    result = minify_at_level(LEVEL_TEST_CODE, 5)
    expected = [
      "module C;T=5;S=1000000000000000000;",
      "def self.a(a) =a*T*S;",
      "def self.b(a,b,c) =a<b ? b : a>c ? c : a;",
      "end;",
      "class B1;",
      "def n =\"base\";",
      "end;",
      "class A<B1;Y=256;B0=%w[low medium high].freeze;A9=%i[add subtract multiply].freeze;",
      "attr :p;",
      "attr :b1,!!1;",
      "def initialize(b,a:\"default\") =(@p=b;@b1=a;@a=[];@@a||=0;@@a+=1;$a=self);",
      "def t(b,a:!1) =(@p=@p+b;@a.push b;a ? \"added\":\"silent\");",
      "def subtract_number(a) =@p-a;",
      "alias neg subtract_number;",
      "def m =@p*A::Y;",
      "def a3 =(@p=0;a=0;a+=1 while a<3;$a=nil;a);",
      "def y =?x;",
      "def g =@p>100?\"big\":\"small\";",
      "def w =(\"non-positive\" unless @p>0);",
      "def process_items(a) =a.each{puts _1};",
      "def a4(a) =begin;@p/a;rescue ZeroDivisionError;0;ensure;@a.push :divide;",
      "end;",
      "def x =case @p;when (0..10);\"low\";when (11..100);\"medium\";else;\"high\";",
      "end;",
      "def r =\"\#{@b1}: \#{@p}\";",
      "def to_s =\"Calculator(\#{@p})\";",
      "def n =super;",
      "def a5 =(yield @p if block_given?);",
      "def a9(a) =(b=[];c=0;until c>=a;c+=1;next if c==2;break if c>4;b.push c;",
      "end;b);",
      "def z =(a=0;begin;a+=1;fail \"fail\" if a<2;a;rescue;retry if a<2;0;end);",
      "def a0 =defined?(@p)?\"yes\":\"no\";",
      "def h(a,b) =(a and !b)?\"a only\":(a or b)?\"at least one\":\"none\";",
      "def q(a) =a&.to_s;",
      "def c(a) =(return \"negative\" if a<0;return \"zero\" if a==0;\"positive\");",
      "def a1;a,*b=1,2,3,4;a+b.size;",
      "end;",
      "def a6(*a,**b) =a.size+b.size;",
      "def a7(&a) =(a.(@p) if a);",
      "def a8 =(a=->(val){val*2};a.(@p));",
      "def v =(a=\"hello\\nworld\\n\";a.strip);",
      "def i(a) =a=~/^calc/i?!!1 : !1;",
      "def b0 =(a=0;for b in [10,20,30];a+=b;",
      "end;a);",
      "def d =(Integer(\"abc\") rescue 0);",
      "def e(a) =!a ? \"nil\":a.to_s;",
      "def b(a) =[1,(2 if a),3].compact;",
      "def o(a) =a.match(/=\\d+/);",
      "def a(a) =(if a;b,c=1,2;else;b,c=3,4;",
      "end;b+c);",
      "def l =[1,2,3].select{|a,b=true|b};",
      "def s =[1,2].map{|b,&a|a ? a.(b):b};",
      "def u =[[1,2,3]].map{|b,*a|b+a.length};",
      "def k =[{a:1}].each{|b,a:false|puts b.inspect};",
      "define_singleton_method(:dsl_method){|a=true|a ? \"yes\":\"no\"};",
      "def f ={[:a,1]=>?x}.each{|(b,c),a|puts \"\#{b}\#{c}\#{a}\"};",
      "def a2 =send :g;",
      "def j(a=nil,&b) =(def b.each =yield call;b);",
      "end;",
      "class V;",
      "def b(c,a:\"\",b:\"\") =\"\#{a}\#{c}\#{b}\";",
      "def a(a) =a==!!1 ? \"yes\":\"no\";",
      "end;",
      "class J;",
      "attr :timeout_ms,!!1;",
      "attr :retry_limit;",
      "def initialize =(@timeout_ms=100;@retry_limit=3);",
      "end;",
      "class L;",
      "def bump_timeout(a) =a.timeout_ms=500;",
      "def raise_timeout(a) =a.timeout_ms+=250;",
      "def show_retries(a) =puts a.retry_limit;",
      "end;",
      "class K;include Comparable;",
      "attr :version_number;",
      "def initialize(a) =@version_number=a;",
      "def <=>(a) =version_number<=>a.version_number;",
      "end;",
      "class A2;",
      "attr :payload_data;",
      "attr_writer :payload_data;",
      "def initialize =@payload_data=1;",
      "end;",
      "class E;",
      "def initialize =@secret_value=42;",
      "def b(other) =other.instance_eval{@secret_value};",
      "def a(a) =instance_variable_get \"@\"+a;",
      "end;",
      "class I;",
      "def initialize =@a=?w;",
      "define_method(:show_label){@a};",
      "end;",
      "class A1;",
      "def self.a(a) =a+10;",
      "end;",
      "class R;",
      "def self.a(a) =a*2;",
      "end;P=[A1,R].freeze;",
      "class G;",
      "def a(a) =case a;in [Integer=>b,*c];\"array head \#{b} rest \#{c.size}\";in {kind: String=>d,value: e};\"hash \#{d} \#{e}\";in Integer | Float=>f if f>100;\"big \#{f}\";in ^((0..10));\"small\";else;\"other\";",
      "end;",
      "def e =(a=[3,7];a=>[b,c];b*c);",
      "def c(a) =(a in {status: :ok});",
      "def d(a) =case a;in [b,*,c];c;else;-1;",
      "end;",
      "def b(a) =case a;in [*b,Symbol=>c,*d];\"\#{b.size}<\#{c}>\#{d.size}\";else;\"none\";",
      "end;",
      "end;",
      "class B;",
      "def initialize(*a) =@a=a;",
      "def [](a) =@a[a];",
      "def []=(a,b);@a[a]=b;",
      "end;",
      "def +(a) =B.new *@a.zip(a.to_a).map(&:sum);",
      "def -@ =B.new(*@a.map{_1*-1});",
      "def to_a =@a;",
      "def ==(a) =to_a==a.to_a;",
      "def call(a) =B.new(*@a.map{_1*a});",
      "def method_missing(a,*b) =a.to_s.start_with?(\"coord_\")?@a[a.to_s.delete_prefix(\"coord_\").to_i]:super;",
      "def respond_to_missing?(a,b=!1) =a.to_s.start_with?(\"coord_\")||super;",
      "end;",
      "class D;A6=255;Z=493;W=10;A5=1000000;A8=1/3r;A3=2i;A4=1500.0;",
      "def b(a) =(b=\"single 'quoted'\";c=\"double \\\"\#{a}\\\"\";d=/go+lf/i;e=:percent_symbol;f=:\"quoted \#{a}\";g=[\"one_\#{a}\",\"two_\#{a}\"];h=\"      no \\\#{interpolation} here\\n\";[b,c,d.source,e,f,g.inspect,h.strip].join \"|\");",
      "def a =[A6,Z,W,A5,A8,A3,A4].join \",\";",
      "end;",
      "class M;",
      "def g =(a=0;begin;a+=1;end while a<3;a);",
      "def e =(1..9).select{!!1 if (_1 == 3)..(_1 == 5)};",
      "def a =(a=0;loop{a+=2;break a if a>5});",
      "def i(a) =catch(:done){(1..).each{throw :done,_1*10 if _1>=a}};",
      "def h(a) =(return 1,2 if a;[3,4]);",
      "def d =[1,2,3,4].map{|a|next 0 if a.odd?;a*a};",
      "def j =(begin;a=7;rescue;a=-1;else;a+=1;ensure;@a=a;",
      "end;a);",
      "def b(a) =a<0?\"neg\":a==0?\"zero\":\"pos\";",
      "def c(a) =[(..5).include?(a),(5..).include?(a)];",
      "def f =[*(?a..?c),*(1..2)];",
      "end;",
      "class F;",
      "def whoami =__method__;",
      "def a =method(:whoami).arity;",
      "def b =(golf_score=42;eval \"golf_score - 2\");",
      "def c(a) =(/(?<num_part>\\d+)-(?<word_part>\\w+)/=~a;\"\#{word_part}:\#{num_part}\");",
      "def d(a) =format \"%05d|%p|%x\",a,a.to_s,a;",
      "end;",
      "class U;",
      "def temp_method =\"gone\";",
      "def a =\"kept\";undef temp_method;",
      "end;",
      "class N;",
      "def original_impl =\"impl\";",
      "alias mirrored original_impl;",
      "end;",
      "class H;",
      "def f(a,b,scale:1) =(a+b)*scale;",
      "def d(...) =f(...);",
      "def c(&) =[1,2].sum(&);",
      "def b(a) =(b=a*2;{width:a,height:b});",
      "def unit_label =\"cm\";",
      "def e(unit_label:) =\"unit=\#{unit_label}\";",
      "def a =e(unit_label:);",
      "end;",
      "class Q;@b=[];class<<self;",
      "attr :b;",
      "def a(a) =@b<<a;",
      "end;",
      "end;O=Struct.new(:x_coord,:y_coord){def magnitude =(x_coord**2+y_coord**2)**0.5};X=Data.define(:col,:row);",
      "class A7<O;",
      "def initialize =super(0,0);",
      "end;calc=A.new 10,a:\"main\";calc.t 5,a:!!1;calc.t 3,a:!1;",
      "puts calc.subtract_number(2);",
      "puts calc.neg(1);",
      "puts calc.m;",
      "puts calc.a3;",
      "puts A::Y;",
      "puts calc.y;",
      "puts calc.g;",
      "puts calc.w;",
      "puts calc.a4(0);",
      "puts calc.x;",
      "puts calc.r;",
      "puts calc.to_s;",
      "puts calc.n;calc.a5{puts _1};",
      "puts calc.a9(5).inspect;",
      "puts calc.z;",
      "puts calc.a0;",
      "puts calc.h(!!1,!1);",
      "puts calc.h(!1,!!1);",
      "puts calc.h(!1,!1);",
      "puts calc.q(\"hello\");",
      "puts calc.q(nil);",
      "puts calc.c(-1);",
      "puts calc.c(0);",
      "puts calc.c(1);",
      "puts calc.a1;",
      "puts calc.a6(1,2,3,a:4);puts(calc.a7{_1+100});",
      "puts calc.a8;",
      "puts calc.v;",
      "puts calc.i(\"calculator\");",
      "puts calc.i(\"other\");",
      "puts calc.b0;",
      "puts calc.d;",
      "puts calc.e(nil);",
      "puts calc.e(\"hi\");",
      "puts calc.b(!!1).inspect;",
      "puts calc.b(!1).inspect;",
      "puts calc.o(\"x=42\");",
      "puts calc.o(\"hello\");",
      "puts calc.a(!!1);",
      "puts calc.a(!1);",
      "puts calc.l.inspect;",
      "puts calc.s.inspect;",
      "puts calc.u.inspect;calc.k;",
      "puts A.dsl_method;",
      "puts A.dsl_method(!1);",
      "puts calc.a2;calc.f;puts(calc.j{\"hello\"}.class);",
      "puts C::T;",
      "puts C.a(7);",
      "puts C.b(150,0,100);fmt=V.new;",
      "puts fmt.b(42,a:\"$\",b:\"!\");",
      "puts fmt.a(!!1);",
      "puts fmt.a(!1);doubled=C.a A::Y;",
      "puts doubled;",
      "puts A::B0.inspect;",
      "puts A::A9.inspect;",
      "puts A0::Status.name;",
      "puts A0::Sys.name;",
      "puts A0::UID.name;",
      "puts A0::GID.name;config=J.new;L.new;",
      "puts config.timeout_ms;",
      "puts config.retry_limit;",
      "puts K.new(1)<K.new(2);payload=A2.new;payload.payload_data=9;",
      "puts payload.payload_data;holder=E.new;",
      "puts holder.b(E.new);",
      "puts holder.a(\"secret_value\");",
      "puts I.new.show_label;puts(P.reduce(5){_2.a _1});pm=G.new;",
      "puts pm.a([5,1]);",
      "puts pm.a({kind:\"gold\",value:3});",
      "puts pm.a(500);",
      "puts pm.a(7);",
      "puts pm.a(?x);",
      "puts pm.e;",
      "puts pm.c({status: :ok});",
      "puts pm.d(%i[a b c]);",
      "puts pm.b([1,2,:mid,3]);",
      "puts pm.b([1,2]);vec=B.new 3,-4;",
      "puts vec[0];vec[1]=5;",
      "puts (vec+B.new(1,1)).to_a.inspect;",
      "puts (-vec).to_a.inspect;",
      "puts vec.(2).to_a.inspect;",
      "puts vec.coord_0;",
      "puts vec==B.new(3,5);ls=D.new;",
      "puts ls.b(?m);",
      "puts ls.a;cg=M.new;",
      "puts cg.g;",
      "puts cg.e.inspect;",
      "puts cg.a;",
      "puts cg.i(4);p cg.h(!!1);",
      "puts cg.d.inspect;",
      "puts cg.j;",
      "puts cg.b(0);",
      "puts cg.c(3).inspect;",
      "puts cg.f.inspect;rg=F.new;",
      "puts rg.whoami;",
      "puts rg.a;",
      "puts rg.b;",
      "puts rg.c(\"42-golf\");",
      "puts rg.d(255);",
      "puts U.new.respond_to?(:temp_method);",
      "puts U.new.a;",
      "puts N.new.mirrored;fg=H.new;",
      "puts fg.d(2,3,scale:2);puts(fg.c{_1*10});",
      "puts fg.b(4).values.inspect;",
      "puts fg.a;Q.a ?x;",
      "puts Q.b.inspect;",
      "puts O.new(3,4).magnitude;",
      "puts X.new(col:1,row:2).row;",
      "puts A7.new.x_coord",
    ].join('')
    assert_equal expected, result.code
    assert_equal 'A0=Process', result.preamble
    assert_equal 'AddStep=A1;AliasedImpl=N;Base=B1;Calculator=A;ControlGolf=M;DoubleStep=R;Formatter=V;ForwardingGolf=H;FrozenPoint=X;GolfVector=B;LabeledWidget=I;LiteralShowcase=D;MathUtils=C;Origin=A7;PIPELINE_STEPS=P;PatternMatcher=G;Payload=A2;PointStruct=O;ReflectionGolf=F;Registry=Q;SecretHolder=E;TimeoutConfig=J;TimeoutTuner=L;Undeffed=U;VersionTag=K;A::LABELS=A::B0;A::OFFSET=A::Y;A::SYMBOLS=A::A9;D::A_THIRD=D::A8;D::BIG_COUNT=D::A5;D::BINARY_FLAGS=D::W;D::FLOAT_EXP=D::A4;D::HEX_MASK=D::A6;D::IMAGINARY=D::A3;D::OCTAL_MODE=D::Z;C::MULTIPLIER=C::T', result.aliases
  end
end
