# frozen_string_literal: true

require_relative 'level_test_helper'

class TestLevel4 < Minitest::Test
  include MinifyTestHelper
  include LevelTestHelper

  # L4: Full variable renaming (locals + keywords + @ivar + @@cvar + $gvar)
  # + class/module constant renaming
  def test_level_4
    result = minify_at_level(LEVEL_TEST_CODE, 4)
    expected = [
      "module C;T=5;S=1000000000000000000;",
      "def self.double_value(a) =a*T*S;",
      "def self.clamp_value(a,b,c) =a<b ? b : a>c ? c : a;",
      "end;",
      "class B1;",
      "def parent_info =\"base\";",
      "end;",
      "class A<B1;Y=256;B0=%w[low medium high].freeze;A9=%i[add subtract multiply].freeze;",
      "attr :current_value;",
      "attr :label,!!1;",
      "def initialize(b,a:\"default\") =(@current_value=b;@label=a;@a=[];@@a||=0;@@a+=1;$a=self);",
      "def add_number(b,a:!1) =(@current_value=@current_value+b;@a.push b;a ? \"added\":\"silent\");",
      "def subtract_number(a) =@current_value-a;",
      "alias neg subtract_number;",
      "def multiply_by_offset =@current_value*A::Y;",
      "def reset_value =(@current_value=0;a=0;a+=1 while a<3;$a=();a);",
      "def get_separator =?x;",
      "def describe_value =@current_value>100?\"big\":\"small\";",
      "def check_positive =(\"non-positive\" unless @current_value>0);",
      "def process_items(a) =a.each{puts _1};",
      "def safe_divide(a) =begin;@current_value/a;rescue ZeroDivisionError;0;ensure;@a.push :divide;",
      "end;",
      "def classify_value =case @current_value;when 0..10;\"low\";when 11..100;\"medium\";else;\"high\";",
      "end;",
      "def value_with_label =\"\#{@label}: \#{@current_value}\";",
      "def to_s =\"Calculator(\#{@current_value})\";",
      "def parent_info =super;",
      "def with_yield =(yield @current_value if block_given?);",
      "def count_up(a) =(b=[];c=0;until c>=a;c+=1;next if c==2;break if c>4;b.push c;",
      "end;b);",
      "def retry_example =(a=0;begin;a+=1;raise \"fail\" if a<2;a;rescue;retry if a<2;0;end);",
      "def check_defined =defined?(@current_value)?\"yes\":\"no\";",
      "def logic_test(a,b) =(a&&!b)?\"a only\":(a||b)?\"at least one\":\"none\";",
      "def safe_access(a) =a&.to_s;",
      "def return_early(a) =(return \"negative\" if a<0;return \"zero\" if a==0;\"positive\");",
      "def multi_assign;a,*b=1,2,3,4;a+b.length;",
      "end;",
      "def splat_args(*a,**b) =a.length+b.length;",
      "def with_block(&a) =(a.(@current_value) if a);",
      "def use_lambda =(a=->(val){val*2};a.(@current_value));",
      "def heredoc_example =(a=\"hello\\nworld\\n\";a.strip);",
      "def regex_example(a) =a=~/^calc/i?!!1 : !1;",
      "def for_loop =(a=0;for b in [10,20,30];a+=b;",
      "end;a);",
      "def rescue_modifier_example =(Integer(\"abc\") rescue 0);",
      "def negated_ternary(a) =!a ? \"nil\":a.to_s;",
      "def array_with_conditional(a) =[1,(2 if a),3].compact;",
      "def regex_match(a) =a.match(/=\\d+/);",
      "def multi_assign_conditional(a) =(if a;b,c=1,2;else;b,c=3,4;",
      "end;b+c);",
      "def with_block_default =[1,2,3].select{|a,b=true|b};",
      "def with_block_param =[1,2].map{|b,&a|a ? a.(b):b};",
      "def with_rest_param =[[1,2,3]].map{|b,*a|b+a.length};",
      "def with_keyword_param =[{a:1}].each{|b,a:false|puts b.inspect};",
      "define_singleton_method(:dsl_method){|a=true|a ? \"yes\":\"no\"};",
      "def destructured_iteration ={[:a,1]=>?x}.each{|(b,c),a|puts \"\#{b}\#{c}\#{a}\"};",
      "def send_example =send :describe_value;",
      "def wrap_in_enumerator(a=(),&b) =(def b.each =yield call;b);",
      "end;",
      "class V;",
      "def format_number(c,a:\"\",b:\"\") =(d=\"\#{a}\#{c}\#{b}\";d);",
      "def format_flag(a) =a==!!1 ? \"yes\":\"no\";",
      "end;",
      "class J;",
      "attr :timeout_ms,!!1;",
      "attr :retry_limit;",
      "def initialize =(@timeout_ms=100;@retry_limit=3);",
      "end;",
      "class L;",
      "def bump_timeout(a) =a.timeout_ms=500;",
      "def raise_timeout(a) =a.timeout_ms+=250;",
      "def show_retries(a) =puts a.retry_limit;",
      "end;",
      "class K;include Comparable;",
      "attr :version_number;",
      "def initialize(a) =@version_number=a;",
      "def <=>(a) =version_number<=>a.version_number;",
      "end;",
      "class A2;",
      "attr :payload_data;",
      "attr_writer :payload_data;",
      "def initialize =@payload_data=1;",
      "end;",
      "class E;",
      "def initialize =@secret_value=42;",
      "def peek_into(other) =other.instance_eval{@secret_value};",
      "def fetch_by_name(a) =instance_variable_get \"@\"+a;",
      "end;",
      "class I;",
      "def initialize =@a=?w;",
      "define_method(:show_label){@a};",
      "end;",
      "class A1;",
      "def self.apply_step(a) =a+10;",
      "end;",
      "class R;",
      "def self.apply_step(a) =a*2;",
      "end;P=[A1,R].freeze;",
      "class G;",
      "def classify(a) =case a;in [Integer=>b,*c];\"array head \#{b} rest \#{c.size}\";in {kind: String=>d,value: e};\"hash \#{d} \#{e}\";in Integer | Float=>f if f>100;\"big \#{f}\";in ^(0..10);\"small\";else;\"other\";",
      "end;",
      "def rightward =(a=[3,7];a=>[b,c];b*c);",
      "def one_line_match?(a) =(a in {status: :ok});",
      "def tail_pattern(a) =case a;in [b,*,c];c;else;-1;",
      "end;",
      "def find_middle(a) =case a;in [*b,Symbol=>c,*d];\"\#{b.size}<\#{c}>\#{d.size}\";in [*,String=>e,*];\"word \#{e}\";else;\"none\";",
      "end;",
      "def only_key(a) =case a;in {id: b,**nil};\"id \#{b}\";else;\"extra\";",
      "end;",
      "end;",
      "class B;",
      "def initialize(*a) =@a=a;",
      "def [](a) =@a[a];",
      "def []=(a,b);@a[a]=b;",
      "end;",
      "def +(a) =B.new *@a.zip(a.to_a).map(&:sum);",
      "def -@ =B.new(*@a.map{_1*-1});",
      "def to_a =@a;",
      "def ==(a) =to_a==a.to_a;",
      "def call(a) =B.new(*@a.map{_1*a});",
      "def method_missing(a,*b) =a.to_s.start_with?(\"coord_\")?@a[a.to_s.delete_prefix(\"coord_\").to_i]:super;",
      "def respond_to_missing?(a,b=!1) =a.to_s.start_with?(\"coord_\")||super;",
      "end;",
      "class D;A6=255;Z=493;W=10;A5=1000000;A8=1/3r;A3=2i;A4=15e2;",
      "def string_forms(a) =(b=\"single 'quoted'\";c=\"double \\\"\#{a}\\\"\";d=/go+lf/i;e=:percent_symbol;f=:\"quoted \#{a}\";g=[\"one_\#{a}\",\"two_\#{a}\"];h=\"      no \\\#{interpolation} here\\n\";[b,c,d.source,e,f,g.inspect,h.strip].join \"|\");",
      "def number_report =[A6,Z,W,A5,A8,A3,A4].join \",\";",
      "end;",
      "class M;",
      "def do_while_count =(a=0;begin;a+=1;end while a<3;a);",
      "def flip_flop_slice =(1..9).select{!!1 if (_1==3)..(_1==5)};",
      "def loop_with_break_value =(a=0;loop{a+=2;break a if a>5});",
      "def throw_catch(a) =catch(:done){(1..).each{throw :done,_1*10 if _1>=a}};",
      "def early_values(a) =(return 1,2 if a;[3,4]);",
      "def block_next_break =[1,2,3,4].map{|a|next 0 if a.odd?;a*a};",
      "def bare_pipes =[1,2].map{:x}+[3].map{t=:y;t};",
      "def begin_else =(begin;a=7;rescue;a=-1;else;a+=1;ensure;@a=a;",
      "end;a);",
      "def case_without_subject(a) =case;when a<0;\"neg\";when a==0;\"zero\";else;\"pos\";",
      "end;",
      "def beginless_endless(a) =[(..5).include?(a),(5..).include?(a)];",
      "def splat_expansion =[*?a..?c,*1..2];",
      "end;",
      "class F;",
      "def whoami =__method__;",
      "def method_ref_arity =method(:whoami).arity;",
      "def eval_with_local =(golf_score=42;eval \"golf_score - 2\");",
      "def named_captures(a) =(/(?<num_part>\\d+)-(?<word_part>\\w+)/=~a;\"\#{word_part}:\#{num_part}\");",
      "def format_report(a) =format \"%05d|%p|%x\",a,a.to_s,a;",
      "end;",
      "class U;",
      "def temp_method =\"gone\";",
      "def kept_method =\"kept\";undef temp_method;",
      "end;",
      "class N;",
      "def original_impl =\"impl\";alias_method :mirrored,:original_impl;",
      "end;",
      "class H;",
      "def base_sum(a,b,scale:1) =(a+b)*scale;",
      "def forward_all(...) =base_sum(...);",
      "def forward_block(&) =[1,2].sum(&);",
      "def shorthand_hash(a) =(b=a*2;{width:a,height:b});",
      "def unit_label =\"cm\";",
      "def describe(unit_label:) =\"unit=\#{unit_label}\";",
      "def punned_describe =describe(unit_label:);",
      "end;",
      "class Q;@entries=[];class<<self;",
      "attr :entries;",
      "def register(a) =@entries<<a;",
      "end;",
      "end;O=Struct.new(:x_coord,:y_coord){def magnitude =(x_coord**2+y_coord**2)**0.5};X=Data.define(:col,:row);",
      "class A7<O;",
      "def initialize =super(0,0);",
      "end;calc=A.new 10,a:\"main\";calc.add_number 5,a:!!1;calc.add_number 3,a:!1;",
      "puts calc.subtract_number(2);",
      "puts calc.neg(1);",
      "puts calc.multiply_by_offset;",
      "puts calc.reset_value;",
      "puts A::Y;",
      "puts calc.get_separator;",
      "puts calc.describe_value;",
      "puts calc.check_positive;",
      "puts calc.safe_divide(0);",
      "puts calc.classify_value;",
      "puts calc.value_with_label;",
      "puts calc.to_s;",
      "puts calc.parent_info;calc.with_yield{puts _1};",
      "puts calc.count_up(5).inspect;",
      "puts calc.retry_example;",
      "puts calc.check_defined;",
      "puts calc.logic_test(!!1,!1);",
      "puts calc.logic_test(!1,!!1);",
      "puts calc.logic_test(!1,!1);",
      "puts calc.safe_access(\"hello\");",
      "puts calc.safe_access(());",
      "puts calc.return_early(-1);",
      "puts calc.return_early(0);",
      "puts calc.return_early(1);",
      "puts calc.multi_assign;",
      "puts calc.splat_args(1,2,3,a:4);puts(calc.with_block{_1+100});",
      "puts calc.use_lambda;",
      "puts calc.heredoc_example;",
      "puts calc.regex_example(\"calculator\");",
      "puts calc.regex_example(\"other\");",
      "puts calc.for_loop;",
      "puts calc.rescue_modifier_example;",
      "puts calc.negated_ternary(());",
      "puts calc.negated_ternary(\"hi\");",
      "puts calc.array_with_conditional(!!1).inspect;",
      "puts calc.array_with_conditional(!1).inspect;",
      "puts calc.regex_match(\"x=42\");",
      "puts calc.regex_match(\"hello\");",
      "puts calc.multi_assign_conditional(!!1);",
      "puts calc.multi_assign_conditional(!1);",
      "puts calc.with_block_default.inspect;",
      "puts calc.with_block_param.inspect;",
      "puts calc.with_rest_param.inspect;calc.with_keyword_param;",
      "puts A.dsl_method;",
      "puts A.dsl_method(!1);",
      "puts calc.send_example;calc.destructured_iteration;puts(calc.wrap_in_enumerator{\"hello\"}.class);",
      "puts C::T;",
      "puts C.double_value(7);",
      "puts C.clamp_value(150,0,100);fmt=V.new;",
      "puts fmt.format_number(42,a:\"$\",b:\"!\");",
      "puts fmt.format_flag(!!1);",
      "puts fmt.format_flag(!1);doubled=C.double_value A::Y;",
      "puts doubled;",
      "puts A::B0.inspect;",
      "puts A::A9.inspect;",
      "puts A0::Status.name;",
      "puts A0::Sys.name;",
      "puts A0::UID.name;",
      "puts A0::GID.name;config=J.new;L.new;",
      "puts config.timeout_ms;",
      "puts config.retry_limit;",
      "puts K.new(1)<K.new(2);payload=A2.new;payload.payload_data=9;",
      "puts payload.payload_data;holder=E.new;",
      "puts holder.peek_into(E.new);",
      "puts holder.fetch_by_name(\"secret_value\");",
      "puts I.new.show_label;puts(P.reduce(5){_2.apply_step _1});pm=G.new;",
      "puts pm.classify([5,1]);",
      "puts pm.classify({kind:\"gold\",value:3});",
      "puts pm.classify(500);",
      "puts pm.classify(7);",
      "puts pm.classify(?x);",
      "puts pm.rightward;",
      "puts pm.one_line_match?({status: :ok});",
      "puts pm.tail_pattern(%i[a b c]);",
      "puts pm.find_middle([1,2,:mid,3]);",
      "puts pm.find_middle([1,?w,2]);",
      "puts pm.find_middle([1,2]);",
      "puts pm.only_key({id:9});",
      "puts pm.only_key({id:9,extra:1});vec=B.new 3,-4;",
      "puts vec[0];vec[1]=5;",
      "puts (vec+B.new(1,1)).to_a.inspect;",
      "puts (-vec).to_a.inspect;",
      "puts vec.(2).to_a.inspect;",
      "puts vec.coord_0;",
      "puts vec==B.new(3,5);ls=D.new;",
      "puts ls.string_forms(?m);",
      "puts ls.number_report;cg=M.new;",
      "puts cg.do_while_count;",
      "puts cg.flip_flop_slice.inspect;",
      "puts cg.loop_with_break_value;",
      "puts cg.throw_catch(4);p cg.early_values(!!1);",
      "puts cg.block_next_break.inspect;",
      "puts cg.bare_pipes.inspect;",
      "puts cg.begin_else;",
      "puts cg.case_without_subject(0);",
      "puts cg.beginless_endless(3).inspect;",
      "puts cg.splat_expansion.inspect;rg=F.new;",
      "puts rg.whoami;",
      "puts rg.method_ref_arity;",
      "puts rg.eval_with_local;",
      "puts rg.named_captures(\"42-golf\");",
      "puts rg.format_report(255);",
      "puts U.new.respond_to?(:temp_method);",
      "puts U.new.kept_method;",
      "puts N.new.mirrored;fg=H.new;",
      "puts fg.forward_all(2,3,scale:2);puts(fg.forward_block{_1*10});",
      "puts fg.shorthand_hash(4).values.inspect;",
      "puts fg.punned_describe;Q.register ?x;",
      "puts Q.entries.inspect;",
      "puts O.new(3,4).magnitude;",
      "puts X.new(col:1,row:2).row;",
      "puts A7.new.x_coord",
    ].join('')
    assert_equal expected, result.code
    assert_equal 'A0=Process', result.preamble
    assert_equal 'AddStep=A1;AliasedImpl=N;Base=B1;Calculator=A;ControlGolf=M;DoubleStep=R;Formatter=V;ForwardingGolf=H;FrozenPoint=X;GolfVector=B;LabeledWidget=I;LiteralShowcase=D;MathUtils=C;Origin=A7;PIPELINE_STEPS=P;PatternMatcher=G;Payload=A2;PointStruct=O;ReflectionGolf=F;Registry=Q;SecretHolder=E;TimeoutConfig=J;TimeoutTuner=L;Undeffed=U;VersionTag=K;A::LABELS=A::B0;A::OFFSET=A::Y;A::SYMBOLS=A::A9;D::A_THIRD=D::A8;D::BIG_COUNT=D::A5;D::BINARY_FLAGS=D::W;D::FLOAT_EXP=D::A4;D::HEX_MASK=D::A6;D::IMAGINARY=D::A3;D::OCTAL_MODE=D::Z;C::MULTIPLIER=C::T', result.aliases
  end
end
