# frozen_string_literal: true

require_relative 'level_test_helper'

class TestLevel2 < Minitest::Test
  include MinifyTestHelper
  include LevelTestHelper

  # L2: Constant aliasing (value constants only) — MULTIPLIER→A, OFFSET→B, SYMBOLS→C, LABELS→D
  # Class/module names stay original: MathUtils, Base, Calculator, Formatter
  def test_level_2
    result = minify_at_level(LEVEL_TEST_CODE, 2)
    expected = [
      "module MathUtils;B=5;S=1000000000000000000;",
      "def self.double_value(number) =number*B*S;",
      "def self.clamp_value(value,min_val,max_val) =value<min_val ? min_val : value>max_val ? max_val : value;",
      "end;",
      "class Base;",
      "def parent_info =\"base\";",
      "end;",
      "class Calculator<Base;D=256;M=%w[low medium high].freeze;K=%i[add subtract multiply].freeze;",
      "attr :current_value;",
      "attr :label,!!1;",
      "def initialize(initial_value,label:\"default\") =(@current_value=initial_value;@label=label;@history=[];@@instance_count||=0;@@instance_count+=1;$last_calculator=self);",
      "def add_number(amount,verbose:!1) =(@current_value=@current_value+amount;@history.push amount;verbose ? \"added\":\"silent\");",
      "def subtract_number(amount) =@current_value-amount;",
      "alias neg subtract_number;",
      "def multiply_by_offset =@current_value*Calculator::D;",
      "def reset_value =(@current_value=0;counter=0;counter+=1 while counter<3;$last_calculator=nil;counter);",
      "def get_separator =?x;",
      "def describe_value =@current_value>100?\"big\":\"small\";",
      "def check_positive =(\"non-positive\" unless @current_value>0);",
      "def process_items(items) =items.each{|item|puts item};",
      "def safe_divide(divisor) =begin;@current_value/divisor;rescue ZeroDivisionError;0;ensure;@history.push :divide;",
      "end;",
      "def classify_value =case @current_value;when (0..10);\"low\";when (11..100);\"medium\";else;\"high\";",
      "end;",
      "def value_with_label =\"\#{@label}: \#{@current_value}\";",
      "def to_s =\"Calculator(\#{@current_value})\";",
      "def parent_info =super;",
      "def with_yield =(yield @current_value if block_given?);",
      "def count_up(limit) =(result=[];idx=0;until idx>=limit;idx+=1;next if idx==2;break if idx>4;result.push idx;",
      "end;result);",
      "def retry_example =(attempts=0;begin;attempts+=1;raise \"fail\" if attempts<2;attempts;rescue;retry if attempts<2;0;end);",
      "def check_defined =defined?(@current_value)?\"yes\":\"no\";",
      "def logic_test(flag_a,flag_b) =(flag_a and !flag_b)?\"a only\":(flag_a or flag_b)?\"at least one\":\"none\";",
      "def safe_access(obj) =obj&.to_s;",
      "def return_early(value) =(return \"negative\" if value<0;return \"zero\" if value==0;\"positive\");",
      "def multi_assign;first,*rest=1,2,3,4;first+rest.length;",
      "end;",
      "def splat_args(*args,**kwargs) =args.length+kwargs.length;",
      "def with_block(&block) =(block.(@current_value) if block);",
      "def use_lambda =(fn=->(val){val*2};fn.(@current_value));",
      "def heredoc_example =(text=\"hello\\nworld\\n\";text.strip);",
      "def regex_example(input) =input=~/^calc/i?!!1 : !1;",
      "def for_loop =(total=0;for num in [10,20,30];total+=num;",
      "end;total);",
      "def rescue_modifier_example =(Integer(\"abc\") rescue 0);",
      "def negated_ternary(val) =!val ? \"nil\":val.to_s;",
      "def array_with_conditional(flag) =[1,(2 if flag),3].compact;",
      "def regex_match(str) =str.match(/=\\d+/);",
      "def multi_assign_conditional(flag) =(if flag;a,b=1,2;else;a,b=3,4;",
      "end;a+b);",
      "def with_block_default =[1,2,3].select{|val,keep=true|keep};",
      "def with_block_param =[1,2].map{|num,&callback|callback ? callback.(num):num};",
      "def with_rest_param =[[1,2,3]].map{|first,*rest|first+rest.length};",
      "def with_keyword_param =[{a:1}].each{|val,flag:false|puts val.inspect};",
      "define_singleton_method(:dsl_method){|verbose=true|verbose ? \"yes\":\"no\"};",
      "def destructured_iteration ={[:a,1]=>?x}.each{|(sym,num),label|puts \"\#{sym}\#{num}\#{label}\"};",
      "def send_example =send :describe_value;",
      "def wrap_in_enumerator(value=nil,&block) =(def block.each =yield call;block);",
      "end;",
      "class Formatter;",
      "def format_number(value,prefix:\"\",suffix:\"\") =(result=\"\#{prefix}\#{value}\#{suffix}\";result);",
      "def format_flag(flag) =flag==!!1 ? \"yes\":\"no\";",
      "end;",
      "class TimeoutConfig;",
      "attr :timeout_ms,!!1;",
      "attr :retry_limit;",
      "def initialize =(@timeout_ms=100;@retry_limit=3);",
      "end;",
      "class TimeoutTuner;",
      "def bump_timeout(target) =target.timeout_ms=500;",
      "def raise_timeout(target) =target.timeout_ms+=250;",
      "def show_retries(target) =puts target.retry_limit;",
      "end;",
      "class VersionTag;include Comparable;",
      "attr :version_number;",
      "def initialize(number) =@version_number=number;",
      "def <=>(other) =version_number<=>other.version_number;",
      "end;",
      "class Payload;",
      "attr :payload_data;",
      "attr_writer :payload_data;",
      "def initialize =@payload_data=1;",
      "end;",
      "class SecretHolder;",
      "def initialize =@secret_value=42;",
      "def peek_into(other) =other.instance_eval{@secret_value};",
      "def fetch_by_name(name) =instance_variable_get \"@\"+name;",
      "end;",
      "class LabeledWidget;",
      "def initialize =@widget_label=?w;",
      "define_method(:show_label){@widget_label};",
      "end;",
      "class AddStep;",
      "def self.apply_step(value) =value+10;",
      "end;",
      "class DoubleStep;",
      "def self.apply_step(value) =value*2;",
      "end;A=[AddStep,DoubleStep].freeze;",
      "class PatternMatcher;",
      "def classify(obj) =case obj;in [Integer=>head,*rest];\"array head \#{head} rest \#{rest.size}\";in {kind: String=>kind,value: value};\"hash \#{kind} \#{value}\";in Integer | Float=>num if num>100;\"big \#{num}\";in ^((0..10));\"small\";else;\"other\";",
      "end;",
      "def rightward =(point=[3,7];point=>[x_pos,y_pos];x_pos*y_pos);",
      "def one_line_match?(value) =(value in {status: :ok});",
      "def tail_pattern(list) =case list;in [_,*,last_el];last_el;else;-1;",
      "end;",
      "def find_middle(list) =case list;in [*front,Symbol=>marker,*back];\"\#{front.size}<\#{marker}>\#{back.size}\";in [*,String=>word,*];\"word \#{word}\";else;\"none\";",
      "end;",
      "def only_key(hash) =case hash;in {id: id,**nil};\"id \#{id}\";else;\"extra\";",
      "end;",
      "end;",
      "class GolfVector;",
      "def initialize(*coords) =@coords=coords;",
      "def [](idx) =@coords[idx];",
      "def []=(idx,val);@coords[idx]=val;",
      "end;",
      "def +(other) =GolfVector.new *@coords.zip(other.to_a).map(&:sum);",
      "def -@ =GolfVector.new(*@coords.map{_1*-1});",
      "def to_a =@coords;",
      "def ==(other) =to_a==other.to_a;",
      "def call(scale) =GolfVector.new(*@coords.map{_1*scale});",
      "def method_missing(name,*args) =name.to_s.start_with?(\"coord_\")?@coords[name.to_s.delete_prefix(\"coord_\").to_i]:super;",
      "def respond_to_missing?(name,include_private=!1) =name.to_s.start_with?(\"coord_\")||super;",
      "end;",
      "class LiteralShowcase;J=255;E=493;C=10;G=1000000;L=1/3r;H=2i;I=1500.0;",
      "def string_forms(unit) =(plain=\"single 'quoted'\";fancy=\"double \\\"\#{unit}\\\"\";pattern=/go+lf/i;sym=:percent_symbol;quoted_sym=:\"quoted \#{unit}\";words=[\"one_\#{unit}\",\"two_\#{unit}\"];raw=\"      no \\\#{interpolation} here\\n\";[plain,fancy,pattern.source,sym,quoted_sym,words.inspect,raw.strip].join \"|\");",
      "def number_report =[J,E,C,G,L,H,I].join \",\";",
      "end;",
      "class ControlGolf;",
      "def do_while_count =(n=0;begin;n+=1;end while n<3;n);",
      "def flip_flop_slice =(1..9).select{|i|!!1 if (i == 3)..(i == 5)};",
      "def loop_with_break_value =(i=0;loop{i+=2;break i if i>5});",
      "def throw_catch(limit) =catch(:done){(1..).each{|i|throw :done,i*10 if i>=limit}};",
      "def early_values(flag) =(return 1,2 if flag;[3,4]);",
      "def block_next_break =[1,2,3,4].map{|i|next 0 if i.odd?;i*i};",
      "def bare_pipes =[1,2].map{:x}+[3].map{t=:y;t};",
      "def begin_else =(begin;value=7;rescue;value=-1;else;value+=1;ensure;@last_value=value;",
      "end;value);",
      "def case_without_subject(n) =case;when n<0;\"neg\";when n==0;\"zero\";else;\"pos\";",
      "end;",
      "def beginless_endless(n) =[(..5).include?(n),(5..).include?(n)];",
      "def splat_expansion =[*(?a..?c),*(1..2)];",
      "end;",
      "class ReflectionGolf;",
      "def whoami =__method__;",
      "def method_ref_arity =method(:whoami).arity;",
      "def eval_with_local =(golf_score=42;eval \"golf_score - 2\");",
      "def named_captures(input) =(/(?<num_part>\\d+)-(?<word_part>\\w+)/=~input;\"\#{word_part}:\#{num_part}\");",
      "def format_report(value) =format \"%05d|%p|%x\",value,value.to_s,value;",
      "end;",
      "class Undeffed;",
      "def temp_method =\"gone\";",
      "def kept_method =\"kept\";undef temp_method;",
      "end;",
      "class AliasedImpl;",
      "def original_impl =\"impl\";alias_method :mirrored,:original_impl;",
      "end;",
      "class ForwardingGolf;",
      "def base_sum(a_val,b_val,scale:1) =(a_val+b_val)*scale;",
      "def forward_all(...) =base_sum(...);",
      "def forward_block(&) =[1,2].sum(&);",
      "def shorthand_hash(width) =(height=width*2;{width:,height:});",
      "def unit_label =\"cm\";",
      "def describe(unit_label:) =\"unit=\#{unit_label}\";",
      "def punned_describe =describe(unit_label:);",
      "end;",
      "class Registry;@entries=[];class<<self;",
      "attr :entries;",
      "def register(name) =@entries<<name;",
      "end;",
      "end;PointStruct=Struct.new(:x_coord,:y_coord){def magnitude =(x_coord**2+y_coord**2)**0.5};FrozenPoint=Data.define(:col,:row);",
      "class Origin<PointStruct;",
      "def initialize =super(0,0);",
      "end;calc=Calculator.new 10,label:\"main\";calc.add_number 5,verbose:!!1;calc.add_number 3,verbose:!1;",
      "puts calc.subtract_number(2);",
      "puts calc.neg(1);",
      "puts calc.multiply_by_offset;",
      "puts calc.reset_value;",
      "puts Calculator::D;",
      "puts calc.get_separator;",
      "puts calc.describe_value;",
      "puts calc.check_positive;",
      "puts calc.safe_divide(0);",
      "puts calc.classify_value;",
      "puts calc.value_with_label;",
      "puts calc.to_s;",
      "puts calc.parent_info;calc.with_yield{|v|puts v};",
      "puts calc.count_up(5).inspect;",
      "puts calc.retry_example;",
      "puts calc.check_defined;",
      "puts calc.logic_test(!!1,!1);",
      "puts calc.logic_test(!1,!!1);",
      "puts calc.logic_test(!1,!1);",
      "puts calc.safe_access(\"hello\");",
      "puts calc.safe_access(nil);",
      "puts calc.return_early(-1);",
      "puts calc.return_early(0);",
      "puts calc.return_early(1);",
      "puts calc.multi_assign;",
      "puts calc.splat_args(1,2,3,a:4);puts(calc.with_block{|v|v+100});",
      "puts calc.use_lambda;",
      "puts calc.heredoc_example;",
      "puts calc.regex_example(\"calculator\");",
      "puts calc.regex_example(\"other\");",
      "puts calc.for_loop;",
      "puts calc.rescue_modifier_example;",
      "puts calc.negated_ternary(nil);",
      "puts calc.negated_ternary(\"hi\");",
      "puts calc.array_with_conditional(!!1).inspect;",
      "puts calc.array_with_conditional(!1).inspect;",
      "puts calc.regex_match(\"x=42\");",
      "puts calc.regex_match(\"hello\");",
      "puts calc.multi_assign_conditional(!!1);",
      "puts calc.multi_assign_conditional(!1);",
      "puts calc.with_block_default.inspect;",
      "puts calc.with_block_param.inspect;",
      "puts calc.with_rest_param.inspect;calc.with_keyword_param;",
      "puts Calculator.dsl_method;",
      "puts Calculator.dsl_method(!1);",
      "puts calc.send_example;calc.destructured_iteration;puts(calc.wrap_in_enumerator{\"hello\"}.class);",
      "puts MathUtils::B;",
      "puts MathUtils.double_value(7);",
      "puts MathUtils.clamp_value(150,0,100);fmt=Formatter.new;",
      "puts fmt.format_number(42,prefix:\"$\",suffix:\"!\");",
      "puts fmt.format_flag(!!1);",
      "puts fmt.format_flag(!1);doubled=MathUtils.double_value Calculator::D;",
      "puts doubled;",
      "puts Calculator::M.inspect;",
      "puts Calculator::K.inspect;",
      "puts F::Status.name;",
      "puts F::Sys.name;",
      "puts F::UID.name;",
      "puts F::GID.name;config=TimeoutConfig.new;TimeoutTuner.new;",
      "puts config.timeout_ms;",
      "puts config.retry_limit;",
      "puts VersionTag.new(1)<VersionTag.new(2);payload=Payload.new;payload.payload_data=9;",
      "puts payload.payload_data;holder=SecretHolder.new;",
      "puts holder.peek_into(SecretHolder.new);",
      "puts holder.fetch_by_name(\"secret_value\");",
      "puts LabeledWidget.new.show_label;puts(A.reduce(5){|acc,step|step.apply_step acc});pm=PatternMatcher.new;",
      "puts pm.classify([5,1]);",
      "puts pm.classify({kind:\"gold\",value:3});",
      "puts pm.classify(500);",
      "puts pm.classify(7);",
      "puts pm.classify(?x);",
      "puts pm.rightward;",
      "puts pm.one_line_match?({status: :ok});",
      "puts pm.tail_pattern(%i[a b c]);",
      "puts pm.find_middle([1,2,:mid,3]);",
      "puts pm.find_middle([1,?w,2]);",
      "puts pm.find_middle([1,2]);",
      "puts pm.only_key({id:9});",
      "puts pm.only_key({id:9,extra:1});vec=GolfVector.new 3,-4;",
      "puts vec[0];vec[1]=5;",
      "puts (vec+GolfVector.new(1,1)).to_a.inspect;",
      "puts (-vec).to_a.inspect;",
      "puts vec.(2).to_a.inspect;",
      "puts vec.coord_0;",
      "puts vec==GolfVector.new(3,5);ls=LiteralShowcase.new;",
      "puts ls.string_forms(?m);",
      "puts ls.number_report;cg=ControlGolf.new;",
      "puts cg.do_while_count;",
      "puts cg.flip_flop_slice.inspect;",
      "puts cg.loop_with_break_value;",
      "puts cg.throw_catch(4);p cg.early_values(!!1);",
      "puts cg.block_next_break.inspect;",
      "puts cg.bare_pipes.inspect;",
      "puts cg.begin_else;",
      "puts cg.case_without_subject(0);",
      "puts cg.beginless_endless(3).inspect;",
      "puts cg.splat_expansion.inspect;rg=ReflectionGolf.new;",
      "puts rg.whoami;",
      "puts rg.method_ref_arity;",
      "puts rg.eval_with_local;",
      "puts rg.named_captures(\"42-golf\");",
      "puts rg.format_report(255);",
      "puts Undeffed.new.respond_to?(:temp_method);",
      "puts Undeffed.new.kept_method;",
      "puts AliasedImpl.new.mirrored;fg=ForwardingGolf.new;",
      "puts fg.forward_all(2,3,scale:2);puts(fg.forward_block{_1*10});",
      "puts fg.shorthand_hash(4).values.inspect;",
      "puts fg.punned_describe;Registry.register ?x;",
      "puts Registry.entries.inspect;",
      "puts PointStruct.new(3,4).magnitude;",
      "puts FrozenPoint.new(col:1,row:2).row;",
      "puts Origin.new.x_coord",
    ].join('')
    assert_equal expected, result.code
    assert_equal 'F=Process', result.preamble
    assert_equal 'PIPELINE_STEPS=A;Calculator::LABELS=Calculator::M;Calculator::OFFSET=Calculator::D;Calculator::SYMBOLS=Calculator::K;LiteralShowcase::A_THIRD=LiteralShowcase::L;LiteralShowcase::BIG_COUNT=LiteralShowcase::G;LiteralShowcase::BINARY_FLAGS=LiteralShowcase::C;LiteralShowcase::FLOAT_EXP=LiteralShowcase::I;LiteralShowcase::HEX_MASK=LiteralShowcase::J;LiteralShowcase::IMAGINARY=LiteralShowcase::H;LiteralShowcase::OCTAL_MODE=LiteralShowcase::E;MathUtils::MULTIPLIER=MathUtils::B', result.aliases
  end
end
