# frozen_string_literal: true

require 'prism'
require 'rbconfig'

require_relative "ryac/errors"
require_relative "ryac/ast_utils"
require_relative "ryac/version"
require_relative "ryac/name_generator"
require_relative "ryac/analysis/method_aliases"
require_relative "ryac/analysis/constant/rename_mapping"
require_relative "ryac/analysis/scope_management"
require_relative "ryac/analysis/local_scopes"
require_relative "ryac/analysis/nesting"
require_relative "ryac/analysis/type_oracle"
require_relative "ryac/analysis/constant/collection"
require_relative "ryac/analysis/method_aliasing"
require_relative "ryac/union_find"
require_relative "ryac/analysis/method/rename_mapping"
require_relative "ryac/analysis/method/collection"
require_relative "ryac/analysis/site_bucket_mapping"
require_relative "ryac/analysis/ivar/collection"
require_relative "ryac/analysis/cvar/collection"
require_relative "ryac/analysis/gvar/rename_mapping"
require_relative "ryac/analysis/gvar/collection"
require_relative "ryac/analysis/keyword/rename_mapping"
require_relative "ryac/analysis/keyword/collection"
require_relative "ryac/minifier"
require_relative "ryac/packer"
require_relative "ryac/gem_resolver"
