# frozen_string_literal: true

module Ryac
  # The two-file layout of a program with lazy regions: the minified program
  # as a pure library — loader, core and aliases, nothing that runs — and a
  # runner holding the regions, which loads the library, registers them and
  # starts the program with an expression given on its command line:
  #
  #   ruby driver.rb minify.rb --exec "Optcarrot::NES.new.run" game.nes
  #
  # The runner strips its own arguments before anything else reads ARGV, so
  # the program's option parsing sees only what follows. Registering after
  # the load means a dynamic require the core runs while loading — rather
  # than from a method called later, the shape that made the file lazy —
  # would miss its region and fall through to the loader's real require.
  module DriverFile
    HEADER = <<~'RUBY'
      # Generated by ryac. Usage: ruby driver.rb CORE [--exec EXPR] [ARGS...]
      # Loads CORE, registers the regions below, then evals EXPR at top level
      # with ARGS left in ARGV. Arguments after "--" are never read.
      core = ARGV.shift or abort("usage: ruby #{$0} CORE [--exec EXPR] [ARGS...]")
      stop = ARGV.index("--")
      at = ARGV.index("--exec")
      expr = ARGV.slice!(at, 2)[1] if at && (!stop || at < stop)
      load core
    RUBY

    FOOTER = "eval(expr, TOPLEVEL_BINDING, \"--exec\") if expr\n"

    # Splits the program's full content into [core, driver]: the region
    # registrations go to the driver, one per line, everything else stays
    # the core in its original order.
    def self.split(full_content)
      result = Prism.parse(full_content)
      raise Pipeline::InvalidOutputError.new('program', result.errors) unless result.errors.none?

      registrations = [] #: Array[String]
      core = [] #: Array[String]
      result.value.statements.body.each do |statement|
        (LazyRegions.registration_lambda(statement) ? registrations : core) << statement.slice
      end
      raise MinifyError, 'cannot write a driver file: the program has no lazy regions' if registrations.empty?

      [core.join(';'), "#{HEADER}#{registrations.join("\n")}\n#{FOOTER}"]
    end
  end
end
