module Ryac
  class GvarRenameMapping
    BUILT_IN_GLOBALS: Set[Symbol]

    @gvars: Hash[Symbol, Array[TypeProf::Core::AST::Node]]
    @excluded_names: Set[Symbol]
    @node_short_names: Hash[[Integer, Integer], String]

    def initialize: () -> void

    def add_site: (Symbol name, TypeProf::Core::AST::Node node) -> void

    def exclude_name: (Symbol name) -> void

    def assign_short_names: () -> void

    def node_mapping: () -> Hash[[Integer, Integer], String]
  end
end
