module Ryac
  module Pipeline
    class AttrDeclShorten < Stage
      include RenamePatcher

      @rename_attrs: bool

      def needs_analysis?: () -> bool
      def initialize: (?rename_attrs: bool) -> void
      def collect: (StageContext ctx, Array[patch_entry] patches) -> void

      private

      def render_attr_declaration: (Symbol type, Array[String] names) -> String?
    end
  end
end
