module Ryac
  module Pipeline
    class CharShorten < Stage
      def collect: (StageContext ctx, Array[patch_entry] patches) -> void

      private

      def walk: (Prism::Node node, Array[patch_entry] patches) -> void
    end
  end
end
