module Ryac
  module Pipeline
    class ConstantAliaser
      include RenamePatcher

      def self.collect_patches_from: (Prism::ProgramNode prism_ast, Array[patch_entry] patches, AnalysisResult analysis, ?Hash[Symbol, String]? kwargs) -> void
      def self.postprocess: (String result, AnalysisResult analysis, String aliases_str, String preamble_str) -> [String, String, String]
      def run_collect: (Prism::ProgramNode node, Array[patch_entry] patches, AnalysisResult analysis, Set[Integer] class_module_cpath_offsets) -> void

      private

      def collect_patches: (Prism::Node node, Array[patch_entry] patches, AnalysisResult analysis) -> void
      def patch_constant_ref: (Prism::Node node, Array[patch_entry] patches, AnalysisResult analysis) -> void
      def patch_constant_write: (Prism::ConstantWriteNode node, Array[patch_entry] patches, AnalysisResult analysis) -> void
      def patch_constant_path_write: (Prism::ConstantPathWriteNode node, Array[patch_entry] patches, AnalysisResult analysis) -> void
      def patch_class_node: (Prism::ClassNode node, Array[patch_entry] patches, AnalysisResult analysis) -> void
      def patch_module_node: (Prism::ModuleNode node, Array[patch_entry] patches, AnalysisResult analysis) -> void
      def mark_constant_children: (Prism::Node node) -> void
      def get_short_cpath: (Array[Symbol] cpath, AnalysisResult analysis) -> String
      def patch_def_receiver: (Prism::Node? receiver, Array[patch_entry] patches, AnalysisResult analysis) -> void
    end
  end
end
