module Ryac
  module Pipeline
    class EndlessMethod
      include SourcePatcher

      def call: (String input) -> String

      private

      def walk: (Prism::Node node, String source, Array[patch_entry] patches) -> void
      def try_def: (Prism::DefNode node, String source) -> String?
      def keyword_logical?: (Prism::Node node, String source) -> bool
    end
  end
end
