module Ryac
  module Pipeline
    class Preprocessor < Stage
      COPS: Array[String]
      CUSTOM_CONFIG: Hash[String, Hash[String, String | bool]]

      def call: (ConcatenatedSource source) -> ConcatenatedSource

      private

      def rubocop_autocorrect: (String source_code) -> String
      def build_processed_source: (String code) -> RuboCop::ProcessedSource
      def cop_registry: () -> RuboCop::Cop::Registry
      def rubocop_config: () -> RuboCop::Config
    end
  end
end
