module Ryac
  module Pipeline
    class Stage
      def call: (String | ConcatenatedSource | DependencyGraph | Array[String] input) -> (String | ConcatenatedSource | AnalysisResult | DependencyGraph)
    end
  end
end
