module Ryac
  module Pipeline
    class UnifiedRenamer
      include RenamePatcher

      type stage_def = [singleton(ConstantAliaser) | singleton(VariableRenamer) | singleton(MethodRenamer)]
                     | [singleton(ConstantAliaser) | singleton(VariableRenamer) | singleton(MethodRenamer), Hash[Symbol, bool]]

      def call: (ConcatenatedSource source, Array[stage_def] stage_defs) -> RenameResult
    end
  end
end
